schema: /Users/takanamito/ghq/github.com/takanamito/gqlgen-todos/graph/schema.graphqls
documents: graphql/**/*.graphql
generates:
  lib/generated/client.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request