import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Todo List</h1>
      <ul>
        <li>todo 1</li>
        <li>todo 2</li>
        <li>todo 3</li>
      </ul>
    </div>
  )
}

export default Home
