import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const todos = [
    { id: 1, body: '目を覚ます' },
    { id: 2, body: '食事をする' },
    { id: 3, body: '歯を磨く' },
  ];

  return (
    <div>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Todo List</h1>
      <ul>
        {todos.map((todo) =>
          <li>{todo.body}</li>
        )}
      </ul>
    </div>
  )
}

export default Home;